### ISSUE TITLE
Error: "Failed to load address parser module"

### ISSUE THREAD

**Issue by puli83** [CSBP-CPSE/OpenBusinessRepository#19]
Hi,
I'm trying to use OpenTabulate to process the "Federal corporations" dataset in 

> LODE-ECDO/sources/Business/.

I've downloaded the following source file: 

> misc/open_data_cfrci.json

I use this command line: 
`opentab --verbose .opentabulate/sources/open_data_cfrc1.json`

Everything if fine until line 237 of "opentab.py" script. In this line we want to import a function `parse_adress` from `postal.parser`. Here the problem, because postal doen't exist.

How can I solve this problem in order to parse "Federal corporations" dataset?

Thank for helpoing me!

**Comment by puli83** [comment]
Sorry,
I did not read well the documentation.  The answer is probably here:

> To process sources with the full_addr key, an address parser is required. Below are the currently supported address parsers. libpostal (and pypostal for Python bindings)

I'll try it and close if I solve the issue.
Sorry

**Comment by mneyrane** [comment]
No worries! You are correct, you will need [libpostal](https://github.com/openvenues/libpostal) and [pypostal](https://github.com/openvenues/pypostal) in this case.
