### ISSUE TITLE
Error in Configuration Error message

### ISSUE THREAD

**Issue by Skye-Chen-CSBP-CPSE** [CSBP-CPSE/OpenBusinessRepository#24]
After running the following command on the command line:
```
$ opentab -s <file_name>.json
```

I got the following error message:

```
Configuration error: Value of label '%s' is not a tuple
```

This is because in the `opentabulate.conf` file, under the `[labels]` section, I had the following key-value pair:
```
metadata = ('localfile')
```
which Python recognizes as just a string, instead of a tuple (as required by opentab). But you can reproduce this error with any value that is not a tuple under the `[labels]` section such as:
```
testing = 7
```

I understand what this error message means and how to fix it, but it would've been more helpful and saved me a bit of time if '%s' was formatted properly to output the key-value pair that was causing the problem.

**Comment by mneyrane** [comment]
Thanks Skye. I merged your changes.
