### ISSUE TITLE
How-to and FAQ

### ISSUE THREAD

**Issue by AugustusBacon** [CSBP-CPSE/OpenBusinessRepository#7]
It would be nice to have a single 1-pager that links to all the resources excellently prepared here so as to achieve at least three functions:
1. transporting/cloning the OBR to a new linux workstation/server environment (and all that it requires); and
2. update the OBR with new municipalities which are not already covered in the existing database
3. update existing municipalities/data sources with new links/sources and potentially new formats. 

Also, a FAQ would be helpful addressing questions such as:
What is the OBR?
What type of data does it use?
How do we use the OBR?
Why was the OBR constructed?
What limitations are present in the OBR?
What is the future of the OBR?

**Comment by mneyrane** [comment]
A wiki will be in the works in the future to organize the documentation. For now, the FAQ is stored alongside other documentation in `docs` [here](https://github.com/CSBP-CPSE/OpenBusinessRepository/blob/master/docs/FAQ.md).

The 1-pager will appear in [README.md](https://github.com/CSBP-CPSE/OpenBusinessRepository/blob/master/README.md).
